server:
  port: 8899

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_APP_ID}
    password: ${EMAIL_APP_PW}
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  application:
    name: gangneung-yeojido
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@mindoroaws.shop:4521/xe
    username: GNTOUR
    password: GNTOUR
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  type-aliases-package: com.gntour.gangneungyeojido
  mapper-locations: classpath:mapper/*.xml